#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/Theo/Documents/School/spring_2019/cs496/exercise_books/PROC

rm -f ast.cmi
rm -f ast.cmo
rm -f ds.cmi
rm -f ds.cmo
rm -f interp.cmi
rm -f interp.cmo
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
# Also clean the script itself
rm -f /mnt/c/Users/Theo/Documents/School/spring_2019/cs496/exercise_books/PROC/_build/sanitize.sh
